export interface NursingHome {
  id: string;
  name: string;
  address: string;
  city: string;
  phone: string;
  accepts_deliveries: boolean;
  delivery_notes?: string;
}

export interface Gift {
  id: string;
  name: string;
  description: string;
  price: number;
  category: "fruit" | "snack" | "comfort" | "flowers" | "activity";
  emoji: string;
  image: string;
  tags: string[];
  popular?: boolean;
  rating: number;
  reviewCount: number;
}

export const nursingHomes: NursingHome[] = [
  {
    id: "nh-1",
    name: "Desert Crest Care Center",
    address: "1633 E Ramon Rd",
    city: "Palm Springs, CA 92264",
    phone: "(760) 323-2337",
    accepts_deliveries: true,
    delivery_notes: "Deliver to front desk Mon–Sat 9am–5pm",
  },
  {
    id: "nh-2",
    name: "Eisenhower Continuing Care at Home",
    address: "39000 Bob Hope Dr",
    city: "Rancho Mirage, CA 92270",
    phone: "(760) 773-4500",
    accepts_deliveries: true,
    delivery_notes: "Call ahead for large deliveries",
  },
  {
    id: "nh-3",
    name: "Sunrise Gardens Senior Living",
    address: "2100 N Indian Canyon Dr",
    city: "Palm Springs, CA 92262",
    phone: "(760) 327-4505",
    accepts_deliveries: true,
  },
  {
    id: "nh-4",
    name: "Desert Haven Assisted Living",
    address: "68780 Grove St",
    city: "Cathedral City, CA 92234",
    phone: "(760) 321-5040",
    accepts_deliveries: true,
    delivery_notes: "Ring buzzer at main entrance",
  },
  {
    id: "nh-5",
    name: "Palm Valley Health Care Center",
    address: "75170 Merle Dr",
    city: "Palm Desert, CA 92211",
    phone: "(760) 341-0261",
    accepts_deliveries: true,
    delivery_notes: "Leave with nursing station 2nd floor if no answer",
  },
  {
    id: "nh-6",
    name: "Vista Cove at Rancho Mirage",
    address: "37301 Cook St",
    city: "Rancho Mirage, CA 92270",
    phone: "(760) 770-8882",
    accepts_deliveries: true,
  },
  {
    id: "nh-7",
    name: "Indio Care & Rehabilitation",
    address: "83775 Avenue 55",
    city: "Indio, CA 92201",
    phone: "(760) 342-6561",
    accepts_deliveries: true,
    delivery_notes: "Deliveries accepted at side entrance",
  },
  {
    id: "nh-8",
    name: "La Quinta Care Center",
    address: "47380 Washington St",
    city: "La Quinta, CA 92253",
    phone: "(760) 564-7200",
    accepts_deliveries: true,
  },
  {
    id: "nh-9",
    name: "Coachella Valley Care Center",
    address: "54905 Golf Course Dr",
    city: "Coachella, CA 92236",
    phone: "(760) 398-0271",
    accepts_deliveries: true,
  },
  {
    id: "nh-10",
    name: "Desert Oasis Skilled Nursing",
    address: "14901 Palm Dr",
    city: "Desert Hot Springs, CA 92240",
    phone: "(760) 329-8131",
    accepts_deliveries: true,
    delivery_notes: "Front desk open 7am–7pm daily",
  },
];

export const gifts: Gift[] = [
  // Soft Fruits
  {
    id: "g-1",
    name: "Hadley's Medjool Date Box",
    description: "1 lb of plump, caramel-soft Medjool dates from the famous Coachella Valley — a Palm Springs icon since 1931.",
    price: 22,
    category: "fruit",
    emoji: "🌴",
    image: "https://images.unsplash.com/photo-1519996529931-28324d5a630e?auto=format&fit=crop&w=600&q=80",
    tags: ["local specialty", "soft", "no pits"],
    popular: true,
    rating: 4.9,
    reviewCount: 312,
  },
  {
    id: "g-2",
    name: "Coachella Navel Oranges",
    description: "6 fresh-picked navel oranges from the sunny Coachella Valley. Sweet, juicy, and easy to peel.",
    price: 16,
    category: "fruit",
    emoji: "🍊",
    image: "https://images.unsplash.com/photo-1582979512210-99b6a53386f9?auto=format&fit=crop&w=600&q=80",
    tags: ["local", "vitamin C", "easy peel"],
    rating: 4.7,
    reviewCount: 89,
  },
  {
    id: "g-3",
    name: "Valley Seedless Red Grapes",
    description: "1 lb of plump, sweet seedless red grapes grown in the Coachella Valley. Washed and ready to enjoy.",
    price: 14,
    category: "fruit",
    emoji: "🍇",
    image: "https://images.unsplash.com/photo-1537640538966-79f369143f8f?auto=format&fit=crop&w=600&q=80",
    tags: ["local", "bite-sized", "no seeds"],
    popular: true,
    rating: 4.6,
    reviewCount: 145,
  },
  {
    id: "g-4",
    name: "Honey Ataulfo Mangos",
    description: "2 perfectly ripe Ataulfo mangos — silky smooth, fiberless, and naturally sweet. The soft mango variety.",
    price: 12,
    category: "fruit",
    emoji: "🥭",
    image: "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?auto=format&fit=crop&w=600&q=80",
    tags: ["soft", "tropical", "fiberless"],
    rating: 4.8,
    reviewCount: 203,
  },
  {
    id: "g-5",
    name: "Fresh Strawberry Basket",
    description: "A pint of local vine-ripened strawberries. Pre-washed and ready to eat — naturally soft and sweet.",
    price: 14,
    category: "fruit",
    emoji: "🍓",
    image: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=600&q=80",
    tags: ["soft", "vitamin C", "local farm"],
    popular: true,
    rating: 4.8,
    reviewCount: 178,
  },
  // Snacks & Treats
  {
    id: "g-6",
    name: "Desert Wildflower Honey",
    description: "A beautiful 12 oz jar of raw local wildflower honey from a Palm Springs beekeeper. Pure, unfiltered desert gold.",
    price: 18,
    category: "snack",
    emoji: "🍯",
    image: "https://images.unsplash.com/photo-1587049352851-8d4e89133924?auto=format&fit=crop&w=600&q=80",
    tags: ["local", "raw", "unfiltered"],
    popular: true,
    rating: 4.9,
    reviewCount: 201,
  },
  {
    id: "g-7",
    name: "Date & Almond Truffles",
    description: "12 handcrafted truffles made with Coachella Valley dates and roasted almonds. Melt-in-your-mouth indulgence.",
    price: 24,
    category: "snack",
    emoji: "🍫",
    image: "https://images.unsplash.com/photo-1549007994-cb92caebd54b?auto=format&fit=crop&w=600&q=80",
    tags: ["local", "handcrafted", "soft"],
    popular: true,
    rating: 4.8,
    reviewCount: 134,
  },
  {
    id: "g-8",
    name: "Palm Springs Bakery Cookies",
    description: "A dozen freshly baked soft cookies from a local Palm Springs bakery: snickerdoodle, oatmeal raisin & shortbread.",
    price: 18,
    category: "snack",
    emoji: "🍪",
    image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=600&q=80",
    tags: ["local bakery", "soft", "variety"],
    rating: 4.7,
    reviewCount: 167,
  },
  {
    id: "g-9",
    name: "Desert Herb Tea Collection",
    description: "20 sachets of handblended herbal teas featuring local desert herbs: chamomile, lavender, and sage.",
    price: 16,
    category: "snack",
    emoji: "🍵",
    image: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?auto=format&fit=crop&w=600&q=80",
    tags: ["local herbs", "caffeine-free", "relaxing"],
    rating: 4.6,
    reviewCount: 92,
  },
  // Comfort Items
  {
    id: "g-10",
    name: "Desert Lavender Spa Kit",
    description: "A soothing set with lavender-infused hand cream, a linen spray, and bath salts — all made with local desert lavender.",
    price: 28,
    category: "comfort",
    emoji: "💜",
    image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=600&q=80",
    tags: ["local lavender", "spa", "relaxing"],
    popular: true,
    rating: 4.8,
    reviewCount: 156,
  },
  {
    id: "g-11",
    name: "Cozy Cotton Throw Blanket",
    description: "An ultra-soft 50×60\" woven cotton throw in warm desert-inspired earth tones. Light enough for Palm Springs evenings.",
    price: 36,
    category: "comfort",
    emoji: "🧣",
    image: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=600&q=80",
    tags: ["soft", "cotton", "earth tones"],
    rating: 4.9,
    reviewCount: 222,
  },
  {
    id: "g-12",
    name: "Non-Slip Slipper Socks",
    description: "Cozy knit slipper socks with rubberized non-slip grips — warm, safe, and perfect for indoor walking.",
    price: 16,
    category: "comfort",
    emoji: "🧦",
    image: "https://images.unsplash.com/photo-1520087619250-584369653c5f?auto=format&fit=crop&w=600&q=80",
    tags: ["safety", "non-slip", "warm"],
    rating: 4.6,
    reviewCount: 78,
  },
  // Flowers
  {
    id: "g-13",
    name: "Desert Sunflower Bouquet",
    description: "8 fresh cut sunflowers arranged by a local Palm Desert florist. Cheerful, bright, and long-lasting.",
    price: 30,
    category: "flowers",
    emoji: "🌻",
    image: "https://images.unsplash.com/photo-1597848212624-a19eb35e2651?auto=format&fit=crop&w=600&q=80",
    tags: ["local florist", "fresh", "long-lasting"],
    popular: true,
    rating: 4.9,
    reviewCount: 287,
  },
  {
    id: "g-14",
    name: "Mojave Succulent Trio",
    description: "Three assorted desert succulents in a terracotta planter. Native to the Coachella Valley — zero maintenance.",
    price: 22,
    category: "flowers",
    emoji: "🌵",
    image: "https://images.unsplash.com/photo-1516048015710-7a3b4c86be43?auto=format&fit=crop&w=600&q=80",
    tags: ["no watering", "native plants", "terracotta"],
    rating: 4.8,
    reviewCount: 198,
  },
  {
    id: "g-15",
    name: "Spring Mixed Bouquet",
    description: "A vibrant seasonal arrangement sourced from local growers — roses, lilies, and wildflowers in a glass vase.",
    price: 38,
    category: "flowers",
    emoji: "💐",
    image: "https://images.unsplash.com/photo-1455582916367-25f75bfc6710?auto=format&fit=crop&w=600&q=80",
    tags: ["local growers", "vase included", "fragrant"],
    popular: true,
    rating: 4.7,
    reviewCount: 143,
  },
  // Activities
  {
    id: "g-16",
    name: "Large-Print Puzzle Book",
    description: "100 large-print crosswords and word searches with a Palm Springs & desert theme. Easy on the eyes.",
    price: 14,
    category: "activity",
    emoji: "📖",
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=600&q=80",
    tags: ["large print", "local theme", "mental stimulation"],
    popular: true,
    rating: 4.7,
    reviewCount: 115,
  },
];

export const categoryLabels: Record<Gift["category"], string> = {
  fruit: "Local Fruit",
  snack: "Snacks & Treats",
  comfort: "Comfort",
  flowers: "Flowers & Plants",
  activity: "Activities",
};
